sonar.projectKey=daohuuduc2003-byte_SIT753---7.3HD-
sonar.organization=daohuuduc2003-byte
sonar.host.url=https://sonarcloud.io
sonar.projectName=River Trail Adventures

sonar.sources=server.py,public
sonar.tests=tests
sonar.exclusions=venv/**,public/images/**
sonar.python.version=3

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

# Stop the pipeline if the quality gate fails
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
